"""test running migrations

Revision ID: 0e9eb20235d8
Revises: c392e5844105
Create Date: 2023-03-04 23:20:44.630316

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "0e9eb20235d8"
down_revision = "c392e5844105"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
