"""test running migrations

Revision ID: 1152e062c56f
Revises: cd011115f8c0
Create Date: 2023-03-05 01:03:47.775814

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "1152e062c56f"
down_revision = "cd011115f8c0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
