"""test running migrations

Revision ID: 1b739ce9aa96
Revises: 1152e062c56f
Create Date: 2023-03-05 01:04:12.147605

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "1b739ce9aa96"
down_revision = "1152e062c56f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
