"""test running migrations

Revision ID: 21679048f2f7
Revises: f6fe94778a92
Create Date: 2023-03-15 00:13:12.345996

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "21679048f2f7"
down_revision = "f6fe94778a92"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
