"""test running migrations

Revision ID: 277e34f74035
Revises: 8f2edc7d7b95
Create Date: 2023-03-05 01:14:15.975120

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "277e34f74035"
down_revision = "8f2edc7d7b95"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
