"""test running migrations

Revision ID: 328e6efac037
Revises: 49632682a132
Create Date: 2023-03-05 01:19:21.719221

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "328e6efac037"
down_revision = "49632682a132"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
