"""test running migrations

Revision ID: 35cc7671ac87
Revises: 6ffe390a993f
Create Date: 2023-03-17 22:42:15.327286

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "35cc7671ac87"
down_revision = "6ffe390a993f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
