"""test running migrations

Revision ID: 389dd3f048a1
Revises: 02c707084417
Create Date: 2023-03-04 23:18:08.689772

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "389dd3f048a1"
down_revision = "02c707084417"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
