"""test running migrations

Revision ID: 3bf862b156cb
Revises: 328e6efac037
Create Date: 2023-03-05 02:40:15.357240

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "3bf862b156cb"
down_revision = "328e6efac037"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
