"""test running migrations

Revision ID: 49632682a132
Revises: ec27fdf4c8c0
Create Date: 2023-03-05 01:17:35.365863

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "49632682a132"
down_revision = "ec27fdf4c8c0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
