"""test running migrations

Revision ID: 4dd0aa8b2c34
Revises: 7849c7bd6405
Create Date: 2023-03-05 00:02:52.203666

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "4dd0aa8b2c34"
down_revision = "7849c7bd6405"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
