"""test running migrations

Revision ID: 6289dbc18123
Revises: caf395f9662f
Create Date: 2023-03-05 01:15:10.241731

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "6289dbc18123"
down_revision = "caf395f9662f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
