"""test running migrations

Revision ID: 6881fea03efc
Revises: cc002a4832ea
Create Date: 2023-03-05 01:01:41.082330

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "6881fea03efc"
down_revision = "cc002a4832ea"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
