"""test running migrations

Revision ID: 6ffe390a993f
Revises: e5d736a756d9
Create Date: 2023-03-17 22:26:44.233714

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "6ffe390a993f"
down_revision = "e5d736a756d9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
