"""test running migrations

Revision ID: 729b226ac37e
Revises: 75c2683746b8
Create Date: 2023-03-17 23:21:37.971208

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "729b226ac37e"
down_revision = "75c2683746b8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
