"""test running migrations

Revision ID: 75c2683746b8
Revises: a95af344cfc5
Create Date: 2023-03-17 22:57:04.316442

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "75c2683746b8"
down_revision = "a95af344cfc5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
