"""test running migrations

Revision ID: 7849c7bd6405
Revises: 872b6a5a5a2e
Create Date: 2023-03-05 00:01:07.693324

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "7849c7bd6405"
down_revision = "872b6a5a5a2e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
