"""test running migrations

Revision ID: 872b6a5a5a2e
Revises: 0e9eb20235d8
Create Date: 2023-03-04 23:32:47.762213

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "872b6a5a5a2e"
down_revision = "0e9eb20235d8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
