"""test running migrations

Revision ID: 8d539ab554fa
Revises: 1b739ce9aa96
Create Date: 2023-03-05 01:04:39.886030

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "8d539ab554fa"
down_revision = "1b739ce9aa96"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
