"""test running migrations

Revision ID: 8ddb5270fc1f
Revises: 4dd0aa8b2c34
Create Date: 2023-03-05 00:06:17.242820

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "8ddb5270fc1f"
down_revision = "4dd0aa8b2c34"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
