"""test running migrations

Revision ID: 8f2edc7d7b95
Revises: a340b575cd87
Create Date: 2023-03-05 01:14:09.242165

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "8f2edc7d7b95"
down_revision = "a340b575cd87"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
