"""test running migrations

Revision ID: 93847ebf3168
Revises: c7a399714759
Create Date: 2023-03-17 02:51:39.176406

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "93847ebf3168"
down_revision = "c7a399714759"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
