"""test running migrations

Revision ID: 9a66ea98d816
Revises: 729b226ac37e
Create Date: 2023-03-17 23:28:50.922042

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "9a66ea98d816"
down_revision = "729b226ac37e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
