"""test running migrations

Revision ID: a340b575cd87
Revises: ee4aa2a86196
Create Date: 2023-03-05 01:12:09.574406

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "a340b575cd87"
down_revision = "ee4aa2a86196"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
