"""test running migrations

Revision ID: a65004f40169
Revises: 8ddb5270fc1f
Create Date: 2023-03-05 00:07:35.423024

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "a65004f40169"
down_revision = "8ddb5270fc1f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
