"""test running migrations

Revision ID: a6c9565cfaac
Revises: 8d539ab554fa
Create Date: 2023-03-05 01:06:01.179896

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "a6c9565cfaac"
down_revision = "8d539ab554fa"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
