"""test running migrations

Revision ID: a95af344cfc5
Revises: 35cc7671ac87
Create Date: 2023-03-17 22:55:39.968706

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "a95af344cfc5"
down_revision = "35cc7671ac87"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
