"""test running migrations

Revision ID: b00f8cac076e
Revises: 389dd3f048a1
Create Date: 2023-03-04 23:19:08.799787

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "b00f8cac076e"
down_revision = "389dd3f048a1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
