"""test running migrations

Revision ID: ba57831b94f3
Revises: 6881fea03efc
Create Date: 2023-03-05 01:03:20.968632

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "ba57831b94f3"
down_revision = "6881fea03efc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
