"""test running migrations

Revision ID: c2aa52b4a129
Revises: a6c9565cfaac
Create Date: 2023-03-05 01:07:56.292551

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "c2aa52b4a129"
down_revision = "a6c9565cfaac"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
