"""test running migrations

Revision ID: c392e5844105
Revises: b00f8cac076e
Create Date: 2023-03-04 23:20:08.757079

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "c392e5844105"
down_revision = "b00f8cac076e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
