"""test running migrations

Revision ID: c7a399714759
Revises: ea5238f7f041
Create Date: 2023-03-15 00:26:22.706541

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "c7a399714759"
down_revision = "ea5238f7f041"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
