"""test running migrations

Revision ID: c86fcc9d8dee
Revises: 231618d4861b
Create Date: 2023-03-04 15:26:51.099969

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "c86fcc9d8dee"
down_revision = "231618d4861b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
