"""test running migrations

Revision ID: caf395f9662f
Revises: 277e34f74035
Create Date: 2023-03-05 01:14:31.354836

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "caf395f9662f"
down_revision = "277e34f74035"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
