"""test running migrations

Revision ID: cc002a4832ea
Revises: f29e324c1f3c
Create Date: 2023-03-05 00:45:30.875206

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "cc002a4832ea"
down_revision = "f29e324c1f3c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
