"""test running migrations

Revision ID: cd011115f8c0
Revises: ba57831b94f3
Create Date: 2023-03-05 01:03:26.463389

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "cd011115f8c0"
down_revision = "ba57831b94f3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
