"""test running migrations

Revision ID: d586dceb0511
Revises: 3bf862b156cb
Create Date: 2023-03-05 02:50:42.497023

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "d586dceb0511"
down_revision = "3bf862b156cb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
