"""test running migrations

Revision ID: e3f37a271ca6
Revises: 9a66ea98d816
Create Date: 2023-03-17 23:33:14.568016

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "e3f37a271ca6"
down_revision = "9a66ea98d816"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
