"""test running migrations

Revision ID: e5d736a756d9
Revises: 93847ebf3168
Create Date: 2023-03-17 03:21:12.834202

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "e5d736a756d9"
down_revision = "93847ebf3168"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
