"""test running migrations

Revision ID: ea5238f7f041
Revises: 21679048f2f7
Create Date: 2023-03-15 00:13:45.686352

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "ea5238f7f041"
down_revision = "21679048f2f7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
