"""test running migrations

Revision ID: ec27fdf4c8c0
Revises: 6289dbc18123
Create Date: 2023-03-05 01:17:11.539729

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "ec27fdf4c8c0"
down_revision = "6289dbc18123"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
