"""test running migrations

Revision ID: ee4aa2a86196
Revises: c2aa52b4a129
Create Date: 2023-03-05 01:08:03.062420

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "ee4aa2a86196"
down_revision = "c2aa52b4a129"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
