"""test running migrations

Revision ID: f29e324c1f3c
Revises: a65004f40169
Create Date: 2023-03-05 00:45:00.195928

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "f29e324c1f3c"
down_revision = "a65004f40169"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
