"""test running migrations

Revision ID: f6fe94778a92
Revises: d586dceb0511
Create Date: 2023-03-05 03:07:29.461641

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "f6fe94778a92"
down_revision = "d586dceb0511"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
